// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: wallet-demo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayId     string                 `protobuf:"bytes,2,opt,name=display_id,json=displayId,proto3" json:"display_id,omitempty"`
	Balance       string                 `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_wallet_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_wallet_demo_proto_rawDescGZIP(), []int{0}
}

func (x *Wallet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Wallet) GetDisplayId() string {
	if x != nil {
		return x.DisplayId
	}
	return ""
}

func (x *Wallet) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type CreateWalletReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletReq) Reset() {
	*x = CreateWalletReq{}
	mi := &file_wallet_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletReq) ProtoMessage() {}

func (x *CreateWalletReq) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletReq.ProtoReflect.Descriptor instead.
func (*CreateWalletReq) Descriptor() ([]byte, []int) {
	return file_wallet_demo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWalletReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetWalletDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayId     string                 `protobuf:"bytes,1,opt,name=display_id,json=displayId,proto3" json:"display_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletDetailReq) Reset() {
	*x = GetWalletDetailReq{}
	mi := &file_wallet_demo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletDetailReq) ProtoMessage() {}

func (x *GetWalletDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_demo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletDetailReq.ProtoReflect.Descriptor instead.
func (*GetWalletDetailReq) Descriptor() ([]byte, []int) {
	return file_wallet_demo_proto_rawDescGZIP(), []int{2}
}

func (x *GetWalletDetailReq) GetDisplayId() string {
	if x != nil {
		return x.DisplayId
	}
	return ""
}

type WalletTransferReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromDisplayId string                 `protobuf:"bytes,1,opt,name=from_display_id,json=fromDisplayId,proto3" json:"from_display_id,omitempty"`
	ToDisplayId   string                 `protobuf:"bytes,2,opt,name=to_display_id,json=toDisplayId,proto3" json:"to_display_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletTransferReq) Reset() {
	*x = WalletTransferReq{}
	mi := &file_wallet_demo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletTransferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletTransferReq) ProtoMessage() {}

func (x *WalletTransferReq) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_demo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletTransferReq.ProtoReflect.Descriptor instead.
func (*WalletTransferReq) Descriptor() ([]byte, []int) {
	return file_wallet_demo_proto_rawDescGZIP(), []int{3}
}

func (x *WalletTransferReq) GetFromDisplayId() string {
	if x != nil {
		return x.FromDisplayId
	}
	return ""
}

func (x *WalletTransferReq) GetToDisplayId() string {
	if x != nil {
		return x.ToDisplayId
	}
	return ""
}

func (x *WalletTransferReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type WalletTransferResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletTransferResp) Reset() {
	*x = WalletTransferResp{}
	mi := &file_wallet_demo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletTransferResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletTransferResp) ProtoMessage() {}

func (x *WalletTransferResp) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_demo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletTransferResp.ProtoReflect.Descriptor instead.
func (*WalletTransferResp) Descriptor() ([]byte, []int) {
	return file_wallet_demo_proto_rawDescGZIP(), []int{4}
}

func (x *WalletTransferResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_wallet_demo_proto protoreflect.FileDescriptor

const file_wallet_demo_proto_rawDesc = "" +
	"\n" +
	"\x11wallet-demo.proto\x12\x05proto\"U\n" +
	"\x06Wallet\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"display_id\x18\x02 \x01(\tR\tdisplayId\x12\x18\n" +
	"\abalance\x18\x03 \x01(\tR\abalance\"%\n" +
	"\x0fCreateWalletReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"3\n" +
	"\x12GetWalletDetailReq\x12\x1d\n" +
	"\n" +
	"display_id\x18\x01 \x01(\tR\tdisplayId\"w\n" +
	"\x11WalletTransferReq\x12&\n" +
	"\x0ffrom_display_id\x18\x01 \x01(\tR\rfromDisplayId\x12\"\n" +
	"\rto_display_id\x18\x02 \x01(\tR\vtoDisplayId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\".\n" +
	"\x12WalletTransferResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xce\x01\n" +
	"\x11WalletDemoService\x125\n" +
	"\fCreateWallet\x12\x16.proto.CreateWalletReq\x1a\r.proto.Wallet\x12;\n" +
	"\x0fGetWalletDetail\x12\x19.proto.GetWalletDetailReq\x1a\r.proto.Wallet\x12E\n" +
	"\x0eWalletTransfer\x12\x18.proto.WalletTransferReq\x1a\x19.proto.WalletTransferRespB(Z&github.com/flametest/wallet-demo/protob\x06proto3"

var (
	file_wallet_demo_proto_rawDescOnce sync.Once
	file_wallet_demo_proto_rawDescData []byte
)

func file_wallet_demo_proto_rawDescGZIP() []byte {
	file_wallet_demo_proto_rawDescOnce.Do(func() {
		file_wallet_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_demo_proto_rawDesc), len(file_wallet_demo_proto_rawDesc)))
	})
	return file_wallet_demo_proto_rawDescData
}

var file_wallet_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_wallet_demo_proto_goTypes = []any{
	(*Wallet)(nil),             // 0: proto.Wallet
	(*CreateWalletReq)(nil),    // 1: proto.CreateWalletReq
	(*GetWalletDetailReq)(nil), // 2: proto.GetWalletDetailReq
	(*WalletTransferReq)(nil),  // 3: proto.WalletTransferReq
	(*WalletTransferResp)(nil), // 4: proto.WalletTransferResp
}
var file_wallet_demo_proto_depIdxs = []int32{
	1, // 0: proto.WalletDemoService.CreateWallet:input_type -> proto.CreateWalletReq
	2, // 1: proto.WalletDemoService.GetWalletDetail:input_type -> proto.GetWalletDetailReq
	3, // 2: proto.WalletDemoService.WalletTransfer:input_type -> proto.WalletTransferReq
	0, // 3: proto.WalletDemoService.CreateWallet:output_type -> proto.Wallet
	0, // 4: proto.WalletDemoService.GetWalletDetail:output_type -> proto.Wallet
	4, // 5: proto.WalletDemoService.WalletTransfer:output_type -> proto.WalletTransferResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wallet_demo_proto_init() }
func file_wallet_demo_proto_init() {
	if File_wallet_demo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_demo_proto_rawDesc), len(file_wallet_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_demo_proto_goTypes,
		DependencyIndexes: file_wallet_demo_proto_depIdxs,
		MessageInfos:      file_wallet_demo_proto_msgTypes,
	}.Build()
	File_wallet_demo_proto = out.File
	file_wallet_demo_proto_goTypes = nil
	file_wallet_demo_proto_depIdxs = nil
}
