// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: wallet-demo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletDemoService_CreateWallet_FullMethodName    = "/proto.WalletDemoService/CreateWallet"
	WalletDemoService_GetWalletDetail_FullMethodName = "/proto.WalletDemoService/GetWalletDetail"
	WalletDemoService_WalletTransfer_FullMethodName  = "/proto.WalletDemoService/WalletTransfer"
)

// WalletDemoServiceClient is the client API for WalletDemoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletDemoServiceClient interface {
	CreateWallet(ctx context.Context, in *CreateWalletReq, opts ...grpc.CallOption) (*Wallet, error)
	GetWalletDetail(ctx context.Context, in *GetWalletDetailReq, opts ...grpc.CallOption) (*Wallet, error)
	WalletTransfer(ctx context.Context, in *WalletTransferReq, opts ...grpc.CallOption) (*WalletTransferResp, error)
}

type walletDemoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletDemoServiceClient(cc grpc.ClientConnInterface) WalletDemoServiceClient {
	return &walletDemoServiceClient{cc}
}

func (c *walletDemoServiceClient) CreateWallet(ctx context.Context, in *CreateWalletReq, opts ...grpc.CallOption) (*Wallet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Wallet)
	err := c.cc.Invoke(ctx, WalletDemoService_CreateWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletDemoServiceClient) GetWalletDetail(ctx context.Context, in *GetWalletDetailReq, opts ...grpc.CallOption) (*Wallet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Wallet)
	err := c.cc.Invoke(ctx, WalletDemoService_GetWalletDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletDemoServiceClient) WalletTransfer(ctx context.Context, in *WalletTransferReq, opts ...grpc.CallOption) (*WalletTransferResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletTransferResp)
	err := c.cc.Invoke(ctx, WalletDemoService_WalletTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletDemoServiceServer is the server API for WalletDemoService service.
// All implementations must embed UnimplementedWalletDemoServiceServer
// for forward compatibility.
type WalletDemoServiceServer interface {
	CreateWallet(context.Context, *CreateWalletReq) (*Wallet, error)
	GetWalletDetail(context.Context, *GetWalletDetailReq) (*Wallet, error)
	WalletTransfer(context.Context, *WalletTransferReq) (*WalletTransferResp, error)
	mustEmbedUnimplementedWalletDemoServiceServer()
}

// UnimplementedWalletDemoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletDemoServiceServer struct{}

func (UnimplementedWalletDemoServiceServer) CreateWallet(context.Context, *CreateWalletReq) (*Wallet, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWallet not implemented")
}
func (UnimplementedWalletDemoServiceServer) GetWalletDetail(context.Context, *GetWalletDetailReq) (*Wallet, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletDetail not implemented")
}
func (UnimplementedWalletDemoServiceServer) WalletTransfer(context.Context, *WalletTransferReq) (*WalletTransferResp, error) {
	return nil, status.Error(codes.Unimplemented, "method WalletTransfer not implemented")
}
func (UnimplementedWalletDemoServiceServer) mustEmbedUnimplementedWalletDemoServiceServer() {}
func (UnimplementedWalletDemoServiceServer) testEmbeddedByValue()                           {}

// UnsafeWalletDemoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletDemoServiceServer will
// result in compilation errors.
type UnsafeWalletDemoServiceServer interface {
	mustEmbedUnimplementedWalletDemoServiceServer()
}

func RegisterWalletDemoServiceServer(s grpc.ServiceRegistrar, srv WalletDemoServiceServer) {
	// If the following call panics, it indicates UnimplementedWalletDemoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletDemoService_ServiceDesc, srv)
}

func _WalletDemoService_CreateWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletDemoServiceServer).CreateWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletDemoService_CreateWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletDemoServiceServer).CreateWallet(ctx, req.(*CreateWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletDemoService_GetWalletDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletDemoServiceServer).GetWalletDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletDemoService_GetWalletDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletDemoServiceServer).GetWalletDetail(ctx, req.(*GetWalletDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletDemoService_WalletTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletTransferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletDemoServiceServer).WalletTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletDemoService_WalletTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletDemoServiceServer).WalletTransfer(ctx, req.(*WalletTransferReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletDemoService_ServiceDesc is the grpc.ServiceDesc for WalletDemoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletDemoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WalletDemoService",
	HandlerType: (*WalletDemoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWallet",
			Handler:    _WalletDemoService_CreateWallet_Handler,
		},
		{
			MethodName: "GetWalletDetail",
			Handler:    _WalletDemoService_GetWalletDetail_Handler,
		},
		{
			MethodName: "WalletTransfer",
			Handler:    _WalletDemoService_WalletTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet-demo.proto",
}
